#+TITLE: Kanata Configuration
#+PROPERTY: header-args :tangle config.kbd :comments both
#+OPTIONS: toc:2 num:nil
 
* Summary
A configuration for kanata that implements the ISRT keyboard layout with homerow modifiers and a custom extend-inspired layer aswell as some other layers and quirks that I use on a daily basis.

* Introduction
This is a literate configuration for the =kanata= program, which is a program one can use on various operating systems to rebind keys on keyboards - even if said keyboard is not programmable. The reason I call this a literate configuration is because this =org-mode= file contains all of the code for the configuration alongside its documentation and can then be "tangled" by the =emacs= text editor into a file that kanata uses. This workflow in general is called =literate programming=.

* Initial Setup
First, set =process-unmapped-keys= to =yes= so that this configuration can work on linux. Then set =concurrent-tap-hold= to =yes=. After that, define what the original keyboard layout looks like. So far, every keyboard I use kanata on has been a standard US Qwerty layout.
#+begin_src lisp
  (defcfg process-unmapped-keys yes
    concurrent-tap-hold yes)

  (defsrc
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
    	caps a    s    d    f    g    h    j    k    l    ;    '    ret
    	lsft z    x    c    v    b    n    m    ,    .    /    rsft
    	lctl lmet lalt           spc            ralt rctl
    	)
#+end_src

* Homerow Modifiers
Homerow Modifiers, like the name suggests, moves modifier keys such as Super (also known as the Windows key), Alt, Control, and Shift to the homerow. This works through giving each key on the homerow a different behavior when tapped and when held. Tapping a homerow key will simply press the key normally whereas holding down a key will have it act as a modifier. This is extremely important to my workflow as I use it probably thousands of times a day as an emacs user. A benefit of using the ISRT keyboard I found after switching is that using that layout with homerow modifiers (and a little help from elisp) makes this layout the perfect layout for emacs keybindings.

I will discuss the ISRT keyboard layout later but for now, the important thing to know is that the homerow keys on qwerty are "asdf" and "jkl;", on ISRT they are "isrt" (hence the name of the layout) and "neao". The following is the implementation of the dual behavior of homerow keys described in the previous paragraph:

First we use the =defalias= feature of kanata to define the special keys, we can use any name here for aliases but I just used the single letters that the alias will replace. In order to get the dual behavior of doing one thing when tapped and another when held, we use the =tap-hold= "function" and the timings to determine what is a tap and what is a hold. I settled on the general values of =300= and =150= but had to change them for the =i= alias because I keep accidentally triggering the held behavior when typing.

The actual modifiers I use are alt for the index finger, control for the middle finger, and shift for the ring finger. I diverge from others using homerow modifiers by having my pinky fingers trigger another layer called =extend= using the function =layer-while-held= which I will explain later. The final crucial thing I add is the =fork= function for the =n= alias, which essentially disables the dual behavior and just sets n to output n even if held - but only if =r/left control= is held first. This is because I use control+n extremely often in emacs and want to be able to hold n down without the dual behavior in that very specific scenario.
#+begin_src lisp

  (defalias
    i (tap-hold  900  150 i (layer-while-held extend))  
    s (tap-hold  300  150 s lalt)
    r (tap-hold  300  150 r lctl)
    t (tap-hold  300  150 t lsft)
    n (fork (tap-hold  300  150 n rsft) n (lctl))
    e (tap-hold  300  150 e rctl)
    a (tap-hold  300  150 a lalt)
    o (tap-hold  300  150 o (layer-while-held extend))
#+end_src

#+begin_src lisp

#+begin_src lisp
    ; (tap-hold  300  150 ; (layer-while-held symbols))
    sym (tap-hold  300  150 (caps-word-toggle 2000) (layer-while-held symbols))
    c (layer-switch gaming)
    arrow (tap-hold 900 300 c (layer-while-held arrow))
    d (tap-hold 900 300 d (layer-while-held numpad))
    rpt (tap-hold 900 300 rpt (layer-while-held numpad))
    0 (tap-hold 300 150 0 S-0)
    1 (tap-hold 300 150 1 S-1)
    2 (tap-hold 300 150 2 S-2)
    3 (tap-hold 300 150 3 S-3)
    4 (tap-hold 300 150 4 S-4)
    5 (tap-hold 300 150 5 S-5)
    6 (tap-hold 300 150 6 S-6)
    7 (tap-hold 300 150 7 S-7)
    8 (tap-hold 300 150 8 S-8)
    9 (tap-hold 300 150 9 S-9)
    msd (movemouse-down 1 1)
    ) 

  (deflayer isrt
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  y    @arrow    l    m    k    z    f    u    ,    '    [    ]    \
    	@sym @i    @s   @r   @t   g    p    @n   @e   @a  @o   @;    ret
    	lmet q    v    w    @d    j    b    h    /    .    x    rmet
    	lctl lmet @rpt           spc            spc rctl
    	)

  ;; (deflayer isrt-left-mods
  ;; 	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  ;; 	tab  y    @arrow    l    m    k    z    f    u    ,    '    [    ]    \
  ;; 	@sym @i    @s   @r   @t   g    p    n   e   a  o  @;    ret
  ;; 	lsft q    v    w    @d    j    b    h    /    .    x    rsft
  ;; 	lctl lmet rpt           spc            spc rctl
  ;; 	)

  ;; (deflayer isrt-right-mods
  ;; 	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  ;; 	tab  y    @arrow    l    m    k    z    f    u    ,    '    [    ]    \
  ;; 	@sym @i    s   r   t   g    p    @n   @e   @a  @o   @;    ret
  ;; 	lsft q    v    w    @d    j    b    h    /    .    x    rsft
  ;; 	lctl lmet rpt           spc            spc rctl
  ;; 	)

  (deflayer extend
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  y    @c   up   down k    z    f    tab    spc    '    [    ]    \
    	caps i    @s   @r   @t   g    p    ret   esc   bspc   o    ;    ret
    	lsft q    v    w    d    j    b    h    /    .    x    rsft
    	lctl lmet lalt           spc            ralt rctl
    	)

  (defalias
      j (tap-hold 200 200 j (movemouse-down 1 1))
    u (tap-hold 200 200 u (movemouse-up 1 1))
    k (tap-hold 200 200 k (movemouse-right 1 1))
    h (tap-hold 200 200 h (movemouse-left 1 1))
    ralt (tap-hold 200 200 mlft ralt)
    rctl (tap-hold 200 200 mrgt rctl)
    phpdot (macro - S-.)
    isrt (layer-switch isrt)
    paren (fork S-9 S-0 (lsft)))

  (deflayer arrow
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  y    c    l    m    k    z    f    u    ,    '    [    ]    \
    	@sym @i    @s   @r   @t   g    left    down   up  right  C-x   @;    ret
    	lsft q    v    w    d    j    b    h    /    .    x    rsft
    	lctl lmet rpt           spc            spc rctl
    	)

  (deflayer gaming
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab \ q    w    e    r    t    y    @u    i   o    p    [    ] 
    	@isrt ret a    s    d    f    g    @h    @j   @k   l   ;    ' 
    	lsft rsft z    x    c    v    b    n    m    ,    .    /
    	@msd lmet lalt           spc            @ralt @rctl
    	)

  (deflayer symbols
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  y    c    l    m    k    z    f    u    ,    '    [    ]    \
    	@sym =    +    -    S-8  /    S-5  @paren  S-[    [  \    ;    ret
    	lsft q    v    w    d    j    b    S-0  S-]    @phpdot   S-\    rsft
    	lctl lmet lalt           spc            ralt rctl
    	)

  (deflayer numpad
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  y    @arrow    l    m  k    z @7   @8  @9  ,  -    ]    \
    	@sym @i    @s   @r   @t   g    p   @4   @5  @6  @0 .    ret
    	lsft q    v    w    d    j    b   @1   @2  @3  .  rsft
    	lctl lmet rpt           spc            spc rctl
    	)

  (deflayer qwerty
    	grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
    	tab  q    w    e    r    t    y    u    i   o    p    [    ] \
    	@isrt a    s    d    f    g    h    j   k   l   ;    ' ret
    	lsft z    x    c    v    b    n    m    ,    .    / rsft
    	@msd lmet lalt           spc            ralt rctl
    	)
#+end_src
